server:
  port: 8884
spring:
  application:
    name: springBoot-canal

#  rabbitmq:
#    host: 122.225.203.87
#    port: 10026
#    username: yq
#    password: yq2018.+
#    virtual-host: /
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  cloud:
    stream:
      bindings:
        canal-sql-out-topic-output:
          destination: canal-sql-out-topic
        canal-sql-out-topic-input:
          destination: canal-sql-out-topic
          group: canal-sql-out-group
          content-type: application/json
          consumer:
            max-attempts: 1
            concurrency: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zsa_food_test_slave?characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

canal:
  databasenames: zsafood_test
  tablenames: accompany_meal_config,message_data_hz
  server:
    #hostname: 122.225.203.87
    #port: 11114
    hostname: 127.0.0.1
    port: 11111
  batch:
    num: 100

connect:
  sleep:
    time: 1000


# mybatis
mybatis:
  mapper-locations: classpath:com.yq.canal.mapper/*.xml
  type-aliases-package: com.yq.canal.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

# tkmapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  identity: MYSQL
#  style: normal

# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  row-bounds-with-count: true
  support-methods-arguments: true

logging:
  level:
    root: info
    com.yq.canal.mapper: debug
  file: logs/${spring.application.name}.log


